// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRM9W-mgCloB2G21ZVB6edxQSRbcJ4gI',
    appId: '1:340528556624:web:d9708a204bfe76a3ffbf55',
    messagingSenderId: '340528556624',
    projectId: 'propel-8f0b6',
    authDomain: 'propel-8f0b6.firebaseapp.com',
    storageBucket: 'propel-8f0b6.firebasestorage.app',
    measurementId: 'G-98KXD0R8LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIBkglbOWY4t6xbFlwyikIneMuJ_vR5L8',
    appId: '1:340528556624:android:749ce0bb710520fcffbf55',
    messagingSenderId: '340528556624',
    projectId: 'propel-8f0b6',
    storageBucket: 'propel-8f0b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCygBon9U_wGG6KlLiLPeQi-AD3H3m5HdA',
    appId: '1:340528556624:ios:fd2f9a9f731980b6ffbf55',
    messagingSenderId: '340528556624',
    projectId: 'propel-8f0b6',
    storageBucket: 'propel-8f0b6.firebasestorage.app',
    iosBundleId: 'com.propel.app.propel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCygBon9U_wGG6KlLiLPeQi-AD3H3m5HdA',
    appId: '1:340528556624:ios:fd2f9a9f731980b6ffbf55',
    messagingSenderId: '340528556624',
    projectId: 'propel-8f0b6',
    storageBucket: 'propel-8f0b6.firebasestorage.app',
    iosBundleId: 'com.propel.app.propel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJRM9W-mgCloB2G21ZVB6edxQSRbcJ4gI',
    appId: '1:340528556624:web:03d1ea8909fd36aeffbf55',
    messagingSenderId: '340528556624',
    projectId: 'propel-8f0b6',
    authDomain: 'propel-8f0b6.firebaseapp.com',
    storageBucket: 'propel-8f0b6.firebasestorage.app',
    measurementId: 'G-5Q8HPE084W',
  );
}
